version: '2'
services:
  eureka:
    image: eureka-server:0.0.1-SNAPSHOT
    ports:
    - "8761:8761"

  client1:
    image: client1:v1
    links:
    - eureka
    - client2
    ports:
    - "8080"

  client3:
    image: client3:v1
    links:
    - eureka
    - client2
    ports:
    - "8082" 
    env_file:
    - client.env

  client2:
    image: client2:v1
    links:
    - eureka
    ports:
    - "8081"

  client2_1:
    image: client2:v1
    links:
    - eureka
    ports:
    - "8081"


