version: '2'
services:
  eureka:
    image: ragovi/eureka-service:0.0.1-SNAPSHOT
    ports:
    - "8761:8761"

  client1:
    image: ragovi/client1:0.0.1-SNAPSHOT
    links:
    - eureka
    - client2
    ports:
    - "8080"

  client3:
    image: ragovi/client3:0.0.1-SNAPSHOT
    links:
    - eureka
    - client2
    ports:
    - "8082" 
    env_file:
    - client.env

  client2:
    image: ragovi/client2:0.0.1-SNAPSHOT
    links:
    - eureka
    ports:
    - "8081"

  client2_1:
    image: ragovi/client2:0.0.1-SNAPSHOT
    links:
    - eureka
    ports:
    - "8081"


